name: Deploy Spring boot to AKS

on:
  push:
    branches: [ main ]
    paths:
      - '.github/github**'

env:
  SPRING_PROFILES_ACTIVE_DEPLOY: cloud

jobs:
  test-package-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.9

      - name: 'Checkout repo'
        uses: actions/checkout@v2

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Package with maven'
        run: mvn clean package
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: 'Save artifact'
        uses: actions/upload-artifact@v1
        with:
          name: marketdata
          path: target

      - name: 'Azure login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Resources to Azure using terraform'
        id: tf_deploy
        run: |
          pushd terraform
            terraform init
            terraform refresh
            terraform plan
            terraform apply --auto-approve
          popd

      - name: 'Push to Azure Container Registry'
        run: |
          docker build -t marketdata .
          az acr login --name myK8sContainerRegistry
          docker tag marketdata:latest myk8scontainerregistry.azurecr.io/marketdata:latest
          docker push myk8scontainerregistry.azurecr.io/marketdata:latest
          registry_images=$(az acr repository list --name myk8scontainerregistry --output table)
          echo "Registry image list = $registry_images"

      - name: 'Deploy to Azure Kubernetes Cluster'
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster
          kubectl apply -f k8s-config.yml
