apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketdata
  template:
    metadata:
      labels:
        app: marketdata
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: marketdata
          image: myk8scontainerregistry.azurecr.io/marketdata:v2
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: marketdata
spec:
  type: LoadBalancer
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: marketdata
