name: Deploy Spring boot to AKS

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'

env:
  APP_NAME: marketdata

  AZURE_RESOURCE_GROUP: k8sResourceGroup
  AZURE_CONTAINER_REGISTRY_NAME: k8smarketdataregistry
  AZURE_KUBERNETES_CLUSTER_NAME: marketdatacluster

  SPRING_PROFILES_ACTIVE_DEPLOY: cloud

  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  package-containerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.9

      - name: 'Checkout repo'
        uses: actions/checkout@v2

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Package with maven'
        run: mvn package
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: 'Save artifact'
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APP_NAME }}
          path: target

      - name: 'Azure login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Resources to Azure using terraform'
        id: tf_deploy
        run: |
          pushd terraform
            terraform init
            terraform plan
            terraform apply --auto-approve
          popd

      - name: 'Push to Azure Container Registry'
        run: |
          docker build -t ${{ env.APP_NAME }} .
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
          docker tag ${{ env.APP_NAME }}:latest ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest
          docker push ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest
          registry_images=$(az acr repository list --name ${{ env.AZURE_CONTAINER_REGISTRY_NAME }} --output table)
          echo "Registry image list = $registry_images"

      - name: 'Deploy to Azure Kubernetes Cluster'
        run: |
          az aks get-credentials --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_KUBERNETES_CLUSTER_NAME }}
          kubectl apply -f k8s-config.yml
